name: Release

on:
  workflow_dispatch:    # Manual trigger
  push:
    branches:
    - ci/automated-build-and-release

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: 📦 Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Build executable
      run: poetry run pyinstaller --onefile --noconsole ./src/main.py

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: jira-tracker
        path: dist/*.exe
        if-no-files-found: error
